// QUERY SELECTORS 🕵️‍♀️
var boxA1 = document.getElementById('a1');
var boxB1 = document.getElementById('b1');
var boxC1 = document.getElementById('c1');
var boxA2 = document.getElementById('a2');
var boxB2 = document.getElementById('b2');
var boxC2 = document.getElementById('c2');
var boxA3 = document.getElementById('a3');
var boxB3 = document.getElementById('b3');
var boxC3 = document.getElementById('c3');
